swagger: "2.0"

info:
    title: Google drive quickstart example
    description: Sample spec
    version: "1.0.0"

schemes:
- https

host: www.googleapis.com

basePath: /drive/v3

produces:
- application/json

consumes:
- application/json

security:
- oauth2: []

securityDefinitions:
    oauth2:
        type: oauth2
        scopes:
            "https://www.googleapis.com/auth/userinfo.email": "Read user email"
            "https://www.googleapis.com/auth/userinfo.profile": "Read user public profile"
            "https://www.googleapis.com/auth/drive": "Write files"
            "https://www.googleapis.com/auth/drive.file": "Manage files"
            "https://www.googleapis.com/auth/drive.metadata": "Manage metadata of files"
        flow: accessCode
        authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth"
        tokenUrl: "https://www.googleapis.com/oauth2/v4/token"
        x-request-token-params:
            access_type: offline
            prompt: consent

paths:
    /about:
        get:
            operationId: get_self
            produces:
            - application/json
            security:
            - oauth2: []
            parameters:
            - name: fields
              in: query
              type: string
              required: true
            responses:
                "200":
                    description: ok
    /files:
        get:
            operationId: search_files
            produces:
            - application/json
            security:
            - oauth2: []
            parameters:
            - name: orderBy
              in: query
              type: string
              required: false
            - name: pageSize
              in: query
              type: integer
              required: false
            - name: pageToken
              in: query
              type: string
              required: false
            - name: q
              in: query
              type: string
              required: false
            - name: fields
              in: query
              type: string
              required: false
            responses:
                "200":
                    description: ok
        post:
            operationId: create_file
            produces:
            - application/json
            security:
            - oauth2: []
            parameters:
            - name: uploadType
              in: query
              type: string
              required: false
            - name: body
              in: body
              type: object
              required: true
              schema:
                  properties:
                      name:
                          type: string
                      parents:
                          type: array
                          items:
                              type: string
                      mimeType:
                          type: string
            responses:
                "200":
                    description: ok
    /files/{fileId}:
        get:
            operationId: get_file
            produces:
            - application/json
            security:
            - oauth2: []
            parameters:
            - name: fileId
              in: path
              type: string
              required: true
            - name: fields
              in: query
              type: string
              required: false
            responses:
                "200":
                    description: ok
        delete:
            operationId: delete_file
            produces:
            - application/json
            security:
            - oauth2: []
            parameters:
            - name: fileId
              in: path
              type: string
              required: true
            responses:
                "200":
                    description: ok
        patch:
            operationId: update_file
            produces:
            - application/json
            security:
            - oauth2: []
            parameters:
            - name: fileId
              in: path
              type: string
              required: true
            - name: uploadType
              in: query
              type: string
              required: false
            - name: body
              in: body
              type: object
              required: true
              schema:
                  properties:
                      name:
                          type: string
                      trashed:
                          type: boolean
            - name: addParents
              in: query
              type: string
              required: false
            - name: removeParents
              in: query
              type: string
              required: false
            responses:
                "200":
                    description: ok
